---
title: "第１講ー２　基本文法"
subtitle: "Python勉強会"
author: Yamato Fujii
format: 
  html: 
    toc: true
    number-sections: true
    echo: true
lang: ja
---

では、基本的な文法を見ていく。

## コメント

Rを使っている皆さんは、`#`でコメントを書けることはご存知だろう。コメントはたくさん残さないと後からコードを確認するときに困るので、しっかり書くようにしよう。

```{python}
# コメント

```


## 変数

**識別子**とは、お互いを識別するための名前のことである。変数は、値を保持するための識別子である。Unicode文字なら絵文字や句読点、アンダースコア以外の記号を除き利用可能だが、慣例的に英数字とアンダースコアを使う**アンダースコア記法**を使うことが多い。（ただし、数字で始められない）

また、予約語は変数名として使えないので注意しよう。

Rでは、`->`を利用して変数に値を代入することができるが、Pythonでは`=`を使う。

```{python}
name = 'Taro'
age = 20
height = 170.5
is_student = True
```

### 命名規則

Pythonでは単語をアンダースコアで区切るスネークケース（snake_case）が一般的である。

```{python}
user_name = 'Taro'
print(user_name)
```

### 変数の破棄

`del`命令を使うことで変数を破棄することができる。

```{python}
#| error: true
name_a = "Python"
print(name_a) #結果: Python

del name_a
print(name_a) #結果: NameError: name 'name_a' is not defined
```

del命令によって、name_aが消去されていることがわかる。

## 定数

変数は値を変更することができるが、定数は値を変更することができない。

では、定数の例を示すため、まずは変数を使用して解説する。

ある商品の税抜き価格`price`に対して、10％の消費税を掛ける計算をする。

```{python}
price = 100
print(price * 1.1) 
```


これでいいのだが、何も知らない人がこのコードを見たとき、この`1.1`が何を表しているのかわからない。値上げ率やサービス料と勘違いするかもしれない。また、消費税率が変わったら、複数あるコードのすべての`1.1`を変えるのが面倒くさい。そこで、定数を使って、`1.1`が消費税率であることを明示する。

```{python}
price = 100
TAX_RATE = 1.1
print(price * TAX_RATE)
```



## データ型

データ型とは、変数が保持する値の種類を表すものである。型によって利用可能な操作や扱い方が異なる。

| 分類 | 型 | 概要 | 変更可能 | 反復可能 | 順序 |
|--------|--------|--------|--------|--------|--------|
| 数値 | `int` | 整数型 | × | × | × |
| 数値 | `float` | 浮動小数点型 | × | × | × |
| 数値 | `complex` | 複素数型 | × | × | × |
| データ | `str` | 文字列型 | × | ○ | ○ |
| データ | `bytes` | バイナリデータ | × | ○ | ○ |
| コンテナー | `list` | 順序を持つリスト| ○ | ○ | ○ |
| コンテナー | `tuple` | 順序を持つリスト（変更不可） | × | ○ | ○ |
| コンテナー | `dict` | キー／値の辞書 | ○ | ○ | ○ |
| コンテナー | `set` | 順序を持たない値の集合 | ○ | ○ | × |
| その他 | `bool` | 論理型（True/False） | × | × | × |
| その他 | `NoneType` | 値なし | × | × | × |


::: {.callout-note}
# 用語

**リテラル**：変数に格納できる値そのもの、またはその表現方法のこと。

:::


### 論理型 `bool`

論理型`bool`は、真（True）か偽（False）の二値を表す型である。ただし、Pythonでは、論理値を必要とする状況で空値（None）、空のシーケンス（''、[]、()）、0などは`False`とみなされる。`False`だけが偽ではないので注意しよう。

### 整数型 `int`

整数を表す型が`int`である。Pythonでは、整数の大きさに制限はない。整数型リテラルは、10進数はもちろんのこと、2進数や16進数、8進数も利用できる。

### 浮動小数点型 `float`
浮動小数点型リテラルは、整数だけでなく小数や指数を表すことができる。

指数表現は、`e`または`E`の後に指数を指定することで表すことができる。

$$
＜仮数部＞e＜符号＞＜指数部＞
$$
の形式で表されるリテラルのこと。

$$
＜仮数部＞*10の＜符号＞＜指数部＞
$$

で本来の小数に変換できる。

Ex）
$$
1.23e4  = 1.23 × 10^4 = 12300
$$

### 複素数型 `complex`

複素数を示します。数学的な計算が必要なければ、あまり使うことはない。

`j`は虚数単位である。

```{python}

c1 = 1.0 + 2.0j #一般的な複素数
c2 = 1.0j #虚数だけの複素数

print(c1 + c2)
```

::: {.callout-note}

複素数はリテラルとして表すほか、`complex()`関数を使って生成することもできる。

```{python}
c = complex(1, 5)
print(c)
```

:::

### 文字列型
文字列リテラルを表すには、シングルクォート`'`またはダブルクォート`"`で囲む。なぜ二種類あるかというと、文字列の中にシングルクォートを含めたい場合はダブルクォートで囲み、文字列の中にダブルクォートを含めたい場合はシングルクォートで囲むといった使い分けによって、文字列の中にシングルクォート`'`またはダブルクォート`"`を含めることができるからである。

```{python}
print('You are "GREAT TEACHER ONIZUKA"!!')
```

ただ、どちらも使う場合は、**エスケープシーケンス記法**を活用する。


::: {.callout-note}

`\'`のことをエスケープシーケンスと呼ぶ。`'`や`"`をはじめ、改行やタブ文字など特別な意味を持つ（ディスプレイに表示不可）などの文字を表すために利用する。

`\`のあとに、入れる記号を入れる。たとえば、`\b`の場合、バックスペースになる。

特にPythonは、**改行すると文が終了判定となるため、改行を含む文字列を表す場合は、`\n`を使う。**

:::
```{python}
print('He\'s a "GREAT TEACHER ONIZUKA"!!')
```

その他、たくさんのリテラル表現があるので、各自で調べてみるとよい。

### リスト

これまでのものは、いずれも単一の値を持つ型であるが、リストは複数の値を持つことができる型である。

例えば、鉄道路線を以下のように定義する。

```{python}
line1 = "東海道線"
line2 = "山手線"
line3 = "中央線"
line4 = "京浜東北線"
line5 = "総武線"
```

しかし、見た目はまとまっているように見えても、実際には、変数がバラバラに定義されているだけであるため、路線の数を数えたり、路線名を列挙したりすることはできない。そこで、リストを使うと、複数の値をまとめて管理することができる。

リストは仕切りのある箱のようなもので、複数の値をまとめて管理することができる。仕切りの中にある値は、**要素**と呼ばれる。リストの要素は、整数や文字列などの単一の値だけでなく、リストや辞書などの複数の値を持つ型も含めることができる。

リストは以下のように作る。

#### １次元リスト

```{python}
data = ['東海道線', '山手線', '中央線', '京浜東北線', '総武線']
```

リストは、カンマ区切りの値をブラケット（`[...]`）でくくった形式で表現する。空のリストは`[]`で表すリストの中身は、`変数名[インデックス番号]`でアクセスすることができる。インデックス番号は、0から始まることに注意。

```{python}
print(data[2])
```

#### ２次元リスト

入れ子のリストを作ることもできる。

```{python}
data_b = [
  ['1-1', '1-2', '1-3'],
  ['2-1', '2-2', '2-3'],
  ['3-1', '3-2', '3-3'],
]

print(data_b[1][2])
```

#### ３次元リスト

二次元リストが何個もある場合は３次元リストとなる

```{python}
data_c = [
  [
    ['1-1-1', '1-1-2', '1-1-3'],
    ['1-2-1', '1-2-2', '1-2-3'],
    ['1-3-1', '1-3-2', '1-3-3'],
  ],
  [
    ['2-1-1', '2-1-2', '2-1-3'],
    ['2-2-1', '2-2-2', '2-2-3'],
    ['2-3-1', '2-3-2', '2-3-3'],
  ],
  [
    ['3-1-1', '3-1-2', '3-1-3'],
    ['3-2-1', '3-2-2', '3-2-3'],
    ['3-3-1', '3-3-2', '3-3-3'],
  ],
]

print(data_c[1][2][0])
```

## 入出力

`print()`関数を使うことで、コンソールに出力することができる。`print()`関数は、引数に指定した値を文字列に変換して出力する。

### 出力

```{python}
print("Hello World")
```

### f文字列

```{python}
name = "Taro"
age = 20

print(f"{name}は{age}歳です")
```



