---
title: "第２講-1　演算子"
subtitle: "Python勉強会"
author: Yamato Fujii
format: 
  html: 
    toc: true
    number-sections: true
    echo: true
lang: ja
---


**演算子（オペレーター）**は、与えられた変数やリテラルに対して、計算や比較などの操作を行う記号である。演算子によって処理される変数／リテラルのことを**被演算子（オペランド）**という。

## 算術演算子
**代数演算子**ともいう。

|演算子|概要|例|
|---|---|---|
|`+`|加算|`2 + 3` → `5`|
|`-`|減算|`5 - 2` → `3`|
|`*`|乗算|`2 * 3` → `6`|
|`/`|除算|`6 / 2` → `3.0`|
|`//`|切り捨て除算|`7 // 2` → `3`|
|`%`|余り|`7 % 2` → `1`|
|`**`|累乗|`2 ** 3` → `8`|

### データ型によって挙動は変化する

数値同士の計算をしたい。$10 + 3 = 13$となるのは自明である。

しかし、

```{python}
print('10' + '3')
```

このように書くと、結果は`103`となる。`'...'`でくくられたリテラルは文字列であり、文字列同士の`+`演算は、加算ではなく文字列の連結となる。

### 文字列と数値の計算

文字列と数値を足し合わせるなどは当然できない。

```{python}
#| error: true
print('20' + 5)
```

よって、数値型`int`などへ変換する。数値型への変換は`int()`関数で変換できる。

```{python}
print(int('20') + 5)
```

### 除算の演算子

除数の演算子は`/`と`//`の二種類ある。
一般的な除数なら、`/`で構わない。しかし、浮動小数点数が出る場合がある。整数部分だけが欲しい場合は、`//`を利用する。

整数部の商と剰余をまとめて得たいならば`divmod()`関数を用いる。

```{python}
print(divmod(5, 3))
```
剰余だけを得たいなら、`%`を用います。


## 代入演算子

左辺で指定した変数に対して右辺の値を設定するための演算子である。`=`はまさしくこの代入演算子である。

| 演算子 | 概要 | 例 |
| :--- | :--- | :--- |
| `=` | 変数などに値を代入 | `x = 10` |
| `+=` | 左辺と右辺を加算した結果を、左辺に代入 | `x = 5; x += 2 ➜ 7` |
| `-=` | 左辺と右辺を減算した結果を、左辺に代入 | `x = 5; x -= 2 ➜ 3` |
| `*=` | 左辺と右辺を乗算した結果を、左辺に代入 | `x = 5; x *= 2 ➜ 10` |
| `/=` | 左辺と右辺を除算した結果を、左辺に代入 | `x = 5; x /= 2 ➜ 2.5` |
| `//=` | 左辺と右辺で除算した結果（整数部）を、左辺に代入 | `x = 5; x //= 2 ➜ 2` |
| `%=` | 左辺と右辺で除算した余りを、左辺に代入 | `x = 5; x %= 2 ➜ 1` |
| `**=` | 左辺を右辺でべき乗した結果を、左辺に代入 | `x = 5; x **= 2 ➜ 25` |
| `&=` | 左辺と右辺をビット論理積した結果を、左辺に代入 | `x = 10; x &= 2 ➜ 2` |
| `^=` | 左辺と右辺をビット排他論理和した結果を、左辺に代入 | `x = 10; x ^= 2 ➜ 8` |
| `|=` | 左辺と右辺をビット論理和した結果を、左辺に代入 | `x = 10; x |= 2 ➜ 10` |
| `>>=` | 左辺を右辺の値だけ右シフトした結果を左辺に代入 | `x = 10; x >>= 2 ➜ 2` |
| `<<=` | 左辺を右辺の値だけ左シフトした結果を左辺に代入 | `x = 10; x <<= 2 ➜ 40`
### 数値のインクリメント・デクリメント

与えられたオペランドに対して、１を加算（`+=`）、減算（`-=`）するための演算子を**インクリメント演算子**／**デクリメント演算子**という。

他言語では、インクリメント演算子は、`++`、デクリメント演算子は、`--`となるため注意が必要。

###  アンパック代入

**アンパック代入**とは、リスト／辞書などを分解し、配下の要素を個々の変数に分解する構文である。
このためには、左辺に要素の数だけ変数を列挙する。

```{python}
data_a = [1, 2, 3, 4, 5]
a, b, c, d, e = data_a
```

こうすると、

```{python}
print(a)
print(b)
print(c)
print(d)
print(e)
```

#### 残りの要素をまとめて代入する

変数に`*`を付与することで、個々の変数に分解されなかった残りの変数をリストとして切り出すこともできる。

```{python}
m, n, *o = data_a #data_aのなかでm=1, n=2, o=残りの3~5と名付けた

print(m)
print(n)
print(o)
```

`*`は末尾である必要はない。ただし、複数には付与できない。

#### 一部要素を切り捨てる

アンパック代入で一部要素が不要な場合、アンダースコア`_`で処理しよう。

```{python}
a, _, b, _, c = data_a #2と4がいらないので切る

print(a)
print(b)
print(c)
print(_) #_が２回あるが、新しい４の方が表示される
```

`*`との併用も可能。

```{python}
x, *_, y = data_a

print(x)
print(y)
print(_)
```

#### 入れ子のリストをアンパックする

入れ子のリストをアンパックすることもできる。


```{python}
data_b = [1, 2, [31, 32, 33]]

a, b, c = data_b #cはまとまりごと指定
print(a)
print(b)
print(c)

```

入れ子の内部まで分解もできる。


```{python}
a, b, (z1, z2, z3) = data_b

print(a)
print(b)
print(z1)
print(z2)
print(z3)

```


#### 実数のスワッピング
アンパック代入は、変数の値を入れ替える（スワッピング）も可能。もし、アンパック代入を用いないのであれば、いずれかの変数をいったん別の変数へ退避させなければいけないため、便利な機能である。

```{python}
x = 15
y = 38
print(x, y)

```
変数をxとyで入れ替えると
```{python}
x, y = y, x

print(x, y)
```

このように入れ替えることができる

## 比較演算子

**比較演算子**（**関係演算子**ともいう）は、左辺と右辺の値を比較し、その結果を`True`か`False`で返す。主に、今後出てくる`if`、`while`、`for`文で多く用いる。

| 演算子 | 概要 | 例 |
| :--- | :--- | :--- |
| `<` | 左辺が右辺より小さい場合にTrue | `5 < 10 ➜ True` |
| `>` | 左辺が右辺より大きい場合にTrue | `5 > 10 ➜ False` |
| `==` | 左辺と右辺の値が等しい場合にTrue | `5 == 5 ➜ True` |
| `<=` | 左辺が右辺以下の場合にTrue | `5 <= 10 ➜ True` |
| `>=` | 左辺が右辺以上の場合にTrue | `5 >= 10 ➜ False` |
| `!=` | 左辺と右辺の値が等しくない場合にTrue | `5 != 10 ➜ True` |
| `is [not]` | 左辺と右辺のオブジェクトが等しい場合にTrue | `[1, 2] is [1, 2] ➜ False` |
| `[not] in` | 左辺が右辺に含まれているか（いないか） | `3 in [1, 2, 3] ➜ True` |


### 異なる型の比較

当然`<`や`>`などの大小比較では、方が違えばエラーで使用できない。問題は、`==`や`!=`は異なる型同士で比較でき、
基本的にFalseを出力することです。

```{python}
print(1 == '1')
print(False == None)
```

ただし、数値型どおしの比較は例外です。


















